<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.json</groupId>
        <artifactId>helidon-json-project</artifactId>
        <version>4.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>helidon-json-codegen</artifactId>
    <name>Helidon Json Code Generator</name>

    <dependencies>
        <dependency>
            <groupId>io.helidon.codegen</groupId>
            <artifactId>helidon-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.codegen</groupId>
            <artifactId>helidon-codegen-class-model</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.helidon.builder</groupId>
                            <artifactId>helidon-builder-codegen</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.codegen</groupId>
                            <artifactId>helidon-codegen-apt</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.common.processor</groupId>
                            <artifactId>helidon-common-processor-helidon-copyright</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>io.helidon.builder</groupId>
                        <artifactId>helidon-builder-processor</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.codegen</groupId>
                        <artifactId>helidon-codegen-apt</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.common.processor</groupId>
                        <artifactId>helidon-common-processor-helidon-copyright</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>


</project>