///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]

:description: Configuration of io.helidon.security.providers.oidc.OidcProvider
:keywords: helidon, config, io.helidon.security.providers.oidc.OidcProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.oidc.OidcProvider

[source,text]
.Type
----
io.helidon.security.providers.oidc.OidcProvider
----

Open ID Connect security provider


[source,text]
.Config key
----
oidc
----

Configuration key:
This type provides the following service implementations:

- `io.helidon.security.spi.AuthenticationProvider`
- `io.helidon.security.spi.SecurityProvider`


==== Configuration options




Optional configuration options:
[cols="3,3,2,5"]

|===
|key |type |default value |description

|`optional` |boolean |`false` |Whether authentication is required.
 By default, request will fail if the authentication cannot be verified.
 If set to true, request will process and this provider will abstain.
|`use-jwt-groups` |boolean |`true` |Claim `groups` from JWT will be used to automatically add
  groups to current subject (may be used with jakarta.annotation.security.RolesAllowed annotation).
|`propagate` |boolean |`false` |Whether to propagate identity.
|`identity-uri` |URI |{nbsp} |URI of the identity server, base used to retrieve OIDC metadata.
|`redirect-uri` |string |`/oidc/redirect` |URI to register web server component on, used by the OIDC server to
 redirect authorization requests to after a user logs in or approves
 scopes.
 Note that usually the redirect URI configured here must be the
 same one as configured on OIDC server.

 <p>
 Defaults to {@value #DEFAULT_REDIRECT_URI}
|`cookie-path` |string |`/` |Path the cookie is valid for.
 Defaults to "/".
|`audience` |string |{nbsp} |Audience of issued tokens.
|`cookie-max-age-seconds` |long |{nbsp} |When using cookie, used to set MaxAge attribute of the cookie, defining how long
 the cookie is valid.
 Not used by default.
|`redirect` |boolean |`false` |By default the client should redirect to the identity server for the user to log in.
 This behavior can be overridden by setting redirect to false. When token is not present in the request, the client
 will not redirect and just return appropriate error response code.
|`proxy-host` |string |{nbsp} |Proxy host to use. When defined, triggers usage of proxy for HTTP requests.
 Setting to empty String has the same meaning as setting to null - disables proxy.
|`query-param-use` |boolean |`false` |Whether to use a query parameter to send JWT token from application to this
 server.
|`proxy-port` |int |`80` |Proxy port.
 Defaults to {@value #DEFAULT_PROXY_PORT}
|`cookie-domain` |string |{nbsp} |Domain the cookie is valid for.
 Not used by default.
|`proxy-protocol` |string |`http` |Proxy protocol to use when proxy is used.
 Defaults to {@value #DEFAULT_PROXY_PROTOCOL}.
|`validate-jwt-with-jwk` |boolean |`true` |Use JWK (a set of keys to validate signatures of JWT) to validate tokens.
 Use this method when you want to use default values for JWK or introspection endpoint URI.
|`max-redirects` |int |`5` |Configure maximal number of redirects when redirecting to an OIDC provider within a single authentication
 attempt.
 <p>
 Defaults to {@value #DEFAULT_MAX_REDIRECTS}
|`client-secret` |string |{nbsp} |Client secret as generated by OIDC server.
 Used to authenticate this application with the server when requesting
 JWT based on a code.
|`frontend-uri` |string |{nbsp} |Full URI of this application that is visible from user browser.
 Used to redirect request back from identity server after successful login.
|`redirect-attempt-param` |string |`h_ra` |Configure the parameter used to store the number of attempts in redirect.
 <p>
 Defaults to {@value #DEFAULT_ATTEMPT_PARAM}
|`cookie-same-site` |SameSite (LAX, STRICT, NONE) |`LAX` |When using cookie, used to set the SameSite cookie value. Can be
 "Strict" or "Lax".
|`authorization-endpoint-uri` |URI |{nbsp} |URI of an authorization endpoint used to redirect users to for logging-in.

 If not defined, it is obtained from #oidcMetadata(Resource), if that is not defined
 an attempt is made to use #identityUri(URI)/oauth2/v1/authorize.
|`oidc-metadata.resource` |link:{rootdir}/includes/config/io.helidon.common.configurable.Resource.adoc[Resource] |{nbsp} |Resource configuration for OIDC Metadata
 containing endpoints to various identity services, as well as information about the identity server.
|`query-param-name` |string |`accessToken` |Name of a query parameter that contains the JWT token when parameter is used.
|`cors` |link:{rootdir}/includes/config/io.helidon.webserver.cors.CrossOriginConfig.adoc[CrossOriginConfig] |{nbsp} |Assign cross-origin resource sharing settings.
|`introspect-endpoint-uri` |URI |{nbsp} |Endpoint to use to validate JWT.
 Either use this or set #signJwk(JwkKeys) or #signJwk(Resource).
|`force-https-redirects` |boolean |`false` |Force HTTPS for redirects to identity provider.
 Defaults to `false`.
|`cookie-http-only` |boolean |`true` |When using cookie, if set to true, the HttpOnly attribute will be configured.
 Defaults to {@value OidcCookieHandler.Builder#DEFAULT_HTTP_ONLY}.
|`client-timeout-millis` |Duration |`30000` |Timeout of calls using web client.
|`header-token` |link:{rootdir}/includes/config/io.helidon.security.util.TokenHandler.adoc[TokenHandler] |{nbsp} |A TokenHandler to
 process header containing a JWT.
 Default is "Authorization" header with a prefix "bearer ".
|`base-scopes` |string |`openid` |Configure base scopes.
 By default this is {@value DEFAULT_BASE_SCOPES}.
 If scope has a qualifier, it must be used here.
|`sign-jwk.resource` |link:{rootdir}/includes/config/io.helidon.common.configurable.Resource.adoc[Resource] |{nbsp} |A resource pointing to JWK with public keys of signing certificates used
 to validate JWT.
|`header-use` |boolean |`true` |Whether to expect JWT in a header field.
|`server-type` |string |`@default` |Configure one of the supported types of identity servers.

 If the type does not have an explicit mapping, a warning is logged and the default implementation is used.
|`issuer` |string |{nbsp} |Issuer of issued tokens.
|`oidc-metadata-well-known` |boolean |`true` |If set to true, metadata will be loaded from default (well known)
 location, unless it is explicitly defined using oidc-metadata-resource. If set to false, it would not be loaded
 even if oidc-metadata-resource is not defined. In such a case all URIs must be explicitly defined (e.g.
 token-endpoint-uri).
|`cookie-secure` |boolean |`false` |When using cookie, if set to true, the Secure attribute will be configured.
 Defaults to false.
|`scope-audience` |string |{nbsp} |Audience of the scope required by this application. This is prefixed to
 the scope name when requesting scopes from the identity server.
 Defaults to empty string.
|`token-endpoint-auth` |ClientAuthentication (CLIENT_SECRET_BASIC, CLIENT_SECRET_POST, CLIENT_SECRET_JWT, PRIVATE_KEY_JWT, NONE) |`CLIENT_SECRET_BASIC` |Type of authentication to use when invoking the token endpoint.
 Current supported options:
 <ul>
     <li>io.helidon.security.providers.oidc.common.OidcConfig.ClientAuthentication#CLIENT_SECRET_BASIC</li>
     <li>io.helidon.security.providers.oidc.common.OidcConfig.ClientAuthentication#CLIENT_SECRET_POST</li>
     <li>io.helidon.security.providers.oidc.common.OidcConfig.ClientAuthentication#NONE</li>
 </ul>
|`cookie-name` |string |`JSESSIONID` |Name of the cookie to use.
 Defaults to {@value #DEFAULT_COOKIE_NAME}.
|`client-id` |string |{nbsp} |Client ID as generated by OIDC server.
|`token-endpoint-uri` |URI |{nbsp} |URI of a token endpoint used to obtain a JWT based on the authentication
 code.
 If not defined, it is obtained from #oidcMetadata(Resource), if that is not defined
 an attempt is made to use #identityUri(URI)/oauth2/v1/token.
|`cookie-use` |boolean |`true` |Whether to use cookie to store JWT between requests.
 Defaults to {@value #DEFAULT_COOKIE_USE}.
|`outbound` |link:{rootdir}/includes/config/io.helidon.security.providers.common.OutboundTarget.adoc[OutboundTarget[&#93;] |{nbsp} |Add a new target configuration.

|===
