///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]

:description: Configuration of io.helidon.security.providers.httpauth.HttpBasicAuthProvider
:keywords: helidon, config, io.helidon.security.providers.httpauth.HttpBasicAuthProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.httpauth.HttpBasicAuthProvider

[source,text]
.Type
----
io.helidon.security.providers.httpauth.HttpBasicAuthProvider
----

HTTP Basic Authentication provider


[source,text]
.Config key
----
http-basic-auth
----

Configuration key:
This type provides the following service implementations:

- `io.helidon.security.spi.SecurityProvider`
- `io.helidon.security.spi.AuthenticationProvider`


==== Configuration options




Optional configuration options:
[cols="3,3,2,5"]

|===
|key |type |default value |description

|`users` |link:{rootdir}/includes/config/io.helidon.security.providers.httpauth.ConfigUserStore.ConfigUser.adoc[ConfigUser[&#93;] |{nbsp} |Set user store to validate users.
 Removes any other stores added through #addUserStore(SecureUserStore).
|`optional` |boolean |`false` |Whether authentication is required.
 By default, request will fail if the authentication cannot be verified.
 If set to false, request will process and this provider will abstain.
|`realm` |string |`helidon` |Set the realm to use when challenging users.
|`principal-type` |SubjectType (USER, SERVICE) |`USER` |Principal type this provider extracts (and also propagates).

|===
